gemeinsam/event/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views
from .models import Event

app_name = "event"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path(
        "occurrence/<int:pk>/",
        views.DetailOccurrenceView.as_view(),
        name="detail-occurrence",
    ),
    path("add/<int:init>/", views.edit, name="add-event"),
    path("edit/<int:id>/", views.edit, name="edit-event"),
    path("calendar/", views.calendar, name="calendar"),
    path("events/", views.events, name="events"),
    path("map/", views.map, name="map"),
    path(
        "data.geojson",
        views.EventMapView.as_view(
            model=Event,
            properties=("title", "topics", "next_occurrence_weekday", "popup_content"),
            geometry_field="coords",
        ),
        name="data",
    ),
]

gemeinsam/faq/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views

app_name = "faq"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("new/", views.new, name="new"),
]

gemeinsam/gemeinsam/urls.py
# Standard Library
import os

# Django stuff
from django.conf import settings

# from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin, flatpages
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import JavaScriptCatalog

# Third party
import home_page

# from newsletter.models import Subscription
# from newsletter_subscription.backend import ModelBackend
# from newsletter_subscription.urls import newsletter_subscriptions_urlpatterns
from pictures.conf import get_settings

# First party
from common import views

urlpatterns = [
    # start-page
    path("", home_page.view),
    path("admin/", admin.site.urls),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("accounts/", include("registration.backends.default.urls")),
    path("accounts/profile/", include("profiles.urls")),
    path("topic/", include("topic.urls")),
    path("initiative/", include("initiative.urls")),
    path("faq/", include("faq.urls")),
    # favicon/robots
    path(
        "favicon.ico",
        RedirectView.as_view(
            url=os.path.join(settings.STATIC_URL, "img", "favicon.ico"), permanent=True
        ),
    ),
    path(
        r"robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # calendar
    path("event/", include("event.urls")),
    # locations
    path("location/", include("location.urls")),
    # search page
    path("search/", include("watson.urls")),
    path("about-us/", flatpages.views.flatpage, {"url": "/about-us/"}, name="about-us"),
    path(
        "participate/",
        flatpages.views.flatpage,
        {"url": "/participate/"},
        name="participate",
    ),
    path("filters/", views.filters),
    # captcha
    path("captcha/", include("captcha.urls")),
]

urlpatterns += [
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if get_settings().USE_PLACEHOLDERS:
    urlpatterns += [
        path("_pictures/", include("pictures.urls")),
    ]

gemeinsam/initiative/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views
from .models import Initiative

app_name = "initiative"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("line/", views.IndexView.as_view(), name="index-line"),
    path("bycounty/", views.IndexViewByCounty.as_view(), name="bycounty"),
    path("bycounty/line", views.IndexViewByCounty.as_view(), name="bycounty-line"),
    path("bytopic/", views.IndexViewByTopic.as_view(), name="bytopic"),
    path("bytopic/line", views.IndexViewByTopic.as_view(), name="bytopic-line"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("add/", views.edit, name="add"),
    path("edit/<int:id>/", views.edit, name="edit"),
    path("update/<str:token>/", views.update, name="update"),
    path(
        "picture-upload/<int:ini>/",
        views.PictureUploadView.as_view(),
        name="picture-upload",
    ),
    path("picture-delete/", views.PictureUploadView.as_view(), name="picture-delete"),
    path("user_list/<int:id>/", views.user_list, name="user_list"),
    path("map/<int:pk>", views.map, name="map-zoom"),
    path("map/", views.map, name="map"),
    path(
        "data.geojson",
        views.InitiativeMapView.as_view(
            model=Initiative,
            properties=("popup_content", "background"),
            geometry_field="coords",
        ),
        name="data",
    ),
]

gemeinsam/location/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views

app_name = "location"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("get_address/", views.get_address, name="get_address"),
    path("add/", views.edit, name="add"),
    path("edit/<int:id>/", views.edit, name="edit"),
]

gemeinsam/location/models.py
# -*- coding: utf-8 -*-


# Django stuff
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.utils.safestring import mark_safe
from django.utils.translation import gettext as _trans
from django.utils.translation import gettext_lazy as _


class Location(models.Model):
    name = models.CharField(_("Name"), max_length=100, blank=True)
    city = models.CharField(_("Ort"), max_length=50, blank=True)
    zipcode = models.CharField(_("PLZ"), max_length=50, blank=True)
    street = models.CharField(_("Straße"), max_length=50, blank=True)
    house_number = models.CharField(_("Hausnr."), max_length=50, blank=True)
    county = models.CharField(_("Bezirk"), max_length=50, blank=True)
    state = models.CharField(_("Bundesland"), max_length=50, blank=True)
    country = models.CharField(_("Land"), max_length=50, blank=True)
    note = models.CharField(_("Bemerkung"), max_length=128, blank=True)
    accessible = models.BooleanField(_("Barrierefreier Zugang"), default=False)
    coords = models.PointField(_("Geographische Koordinaten"), srid=4326, dim=2)
    creator = models.ForeignKey(
        User,
        related_name="creator+",
        on_delete=models.CASCADE,
        verbose_name=_("Ersteller*in"),
    )

    class Meta:
        verbose_name = _("Ort")
        verbose_name_plural = _("Orte")
        ordering = ("name", "city", "street")

    def __str__(self):
        address_str = self.address_formatted(for_choice=True)
        if self.name:
            return f"{self.name} ({address_str})"
        else:
            return address_str

    def coords_formatted(self):
        return "{:.4f}, {:.4f}".format(*self.coords.tuple)

    coords_formatted.short_description = _("Koordinaten")

    def address_formatted(self, for_choice=False):
        street_part = " ".join([_f for _f in [self.street, self.house_number] if _f])
        city_part = " ".join([_f for _f in [self.zipcode, self.city] if _f])
        accessible = ""
        if self.accessible:
            accessible = (
                for_choice
                and _trans("barrierefrei")
                or "<i class='fa fa-wheelchair' aria-hidden='true'></i>"
            )
        return mark_safe(
            ", ".join(
                [_f for _f in [self.name, street_part, city_part, accessible] if _f]
            )
        )

    address_formatted.short_description = _("Adresse")


def locations_as_choices(user=None, id=None, restriction=False):
    # Django stuff
    from django.db.models import Q

    query = Q()
    if user:
        query |= Q(creator=user)
    if id:
        query |= Q(pk=id)

    if restriction and hasattr(settings, "LOCATION_REGION_FORCE"):
        field, region = [settings.LOCATION_REGION_FORCE[x] for x in ["field", "name"]]
        query &= Q(**{field: region})

    locations = {}
    for location in Location.objects.filter(query):
        locations.setdefault(location.city, []).append(
            [location.pk, location.__str__()]
        )

    locations_list = [[k, v] for k, v in list(locations.items())]
    return sorted(locations_list, key=lambda x: x[0])


def location_states_counties_dict():
    states = []

    tmp = {}
    for result in (
        Location.objects.all()
        .order_by("state", "county")
        .distinct("state", "county")
        .values("state", "county")
    ):
        tmp.setdefault(result["state"], []).append(result["county"])

    for state in sorted(tmp.keys()):
        states.append({"name": state, "counties": [{"name": x} for x in tmp[state]]})

    return states

gemeinsam/location/forms.py
# -*- coding: utf-8 -*-
# Django stuff
from django import forms
from django.utils.translation import gettext_lazy as _

# Third party
from leaflet.forms.widgets import LeafletWidget

# Local imports
from .models import Location


class LocationForm(forms.ModelForm):
    deletion = forms.BooleanField(required=False, label=_("Unwiderruflich löschen"))

    class Meta:
        model = Location
        exclude = ["creator"]
        widgets = {
            "coords": LeafletWidget(),
        }

    def __init__(self, *args, **kwargs):
        super(LocationForm, self).__init__(*args, **kwargs)

        for field in self.fields:
            if field not in ["deletion", "accessible"]:
                self.fields[field].widget.attrs.update(
                    {"class": "form-control", "placeholder": self.fields[field].label}
                )
                if field in [
                    "street",
                    "house_number",
                    "city",
                    "zipcode",
                    "country",
                    "county",
                    "state",
                ]:
                    self.fields[field].widget.attrs["readonly"] = True

gemeinsam/location/views.py
# -*- coding: utf-8 -*-


# Standard Library
import json

# Django stuff
# 'globals'
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import generic

from geopy.exc import GeocoderServiceError

# Local imports
from .apps import GEOCODE2MODELFIELD, MAP_STRINGS
from .forms import LocationForm
from .models import Location
from .utils import geocode_reverse

# Create your views here.


class DetailView(generic.DetailView):
    context_object_name = "location"
    template_name = "location/detail.html"
    model = Location


def get_address(request):
    """
    Returns a json-response with postal address data for
    geographical coordingates. It uses the geopy project
    as geocoder interface.
    """
    if (
        request.headers.get("x-requested-with") == "XMLHttpRequest"
        and request.method == "POST"
    ):
        data = json.loads(request.body)
        status_code = 200
        try:
            address = geocode_reverse((data["lat"], data["lng"]))
        except GeocoderServiceError:
            status_code = 404
            address = {
                "status": _(
                    "Geocoder im Moment nicht erreichbar. Bitte versuche es später nocheinmal"
                )
            }

        if "region" in data and hasattr(settings, "LOCATION_REGION_FORCE"):
            field, region = [
                settings.LOCATION_REGION_FORCE[x] for x in ["field", "name"]
            ]

            if field not in address or address[field] != region:
                status_code = 404
                address["status"] = _("Ort liegt nicht in: {}".format(region))

        address["code"] = status_code
        return JsonResponse(data=address)


@login_required
def edit(request, id=None):
    if id:
        location = get_object_or_404(Location, pk=id)

        # check permission
        if not request.user.has_perm("location.change_location", location):
            raise PermissionDenied

    else:
        location = Location(creator=request.user)

    if request.method == "POST":
        # check if user wants to delete this location
        if request.POST.get("loc-deletion"):
            location.delete()
            return HttpResponseRedirect("/")

        form = LocationForm(request.POST, prefix="loc", instance=location)

        if form.is_valid():
            location = form.save()
            return HttpResponseRedirect(reverse("location:detail", args=[location.pk]))

    else:
        form = LocationForm(instance=location, prefix="loc")

    return render(
        request,
        "location/edit.html",
        {
            "form": form,
            "map_strings": MAP_STRINGS,
            "geocode2modelfield": GEOCODE2MODELFIELD,
            "settings": {
                "MODERATION_EMAIL": settings.MODERATION_EMAIL,
                "PELIAS_API_KEY": settings.PELIAS_API_KEY,
                "PELIAS_URL": settings.PELIAS_URL,
            },
        },
    )

gemeinsam/location/templates/location/address.html
{% load i18n %}
{% if on_line %}
<em>{% trans "On-line Treffen" %}</em>
{% else %}
{% if location %}
{% if location.name %}<b>{{ location.name }}</b><br/>{% endif %}
{% if location.street %}{{ location.street }} {{ location.house_number }}<br/>{% endif %}
{% if location.city %}{{ location.zipcode }} {{ location.city }}{% endif %}
{% if location.note %}<br/><i>{{ location.note }}</i>{% endif %}
{% if location.accessible %}<br/><i class="fa fa-wheelchair" aria-hidden="true"></i>{% endif %}
{% else %}
<em class="text-warning">{% trans "Noch nicht bekannt" %}</em>
{% endif %}
{% endif %}

gemeinsam/location/templates/location/detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load leaflet_tags %}
{% block title %}{% trans "Detail Ort" %}{% endblock title %}
{% block css %}
{% leaflet_css %}
<link rel="stylesheet" href="{% static 'leaflet-defaulticon-compatibility/dist/leaflet-defaulticon-compatibility.css' %}"/>
{% endblock css %}
{% block js %}
{% leaflet_js %}
<script type="text/javascript" src="{% static 'leaflet-defaulticon-compatibility/dist/leaflet-defaulticon-compatibility.min.js' %}"></script>
{% endblock js %}

{% block content %}
<section class="mt-3">
  <div class="row d-flex gy-3 justify-content-around flex-md-row flex-column">
    <div class="col-12 col-md-8">
      <h3>{% trans 'Karte' %}</h3>
      {% with lon=location.coords.x|safe lat=location.coords.y|safe %}
      <script type="text/javascript">
	function map_init(map, options) {
            L.marker([{{ lat }}, {{ lon }}]).addTo(map);
            map.setView(L.latLng({{ lat }}, {{ lon }}), 16);
	}
      </script>
      {% endwith %}
      <div>
	{% leaflet_map "main" callback="window.map_init" %}
      </div>
    </div>

    <div class="col-12 col-md-4">
      <h3>{% trans 'Info' %}</h3>
      <div class="mb-2">
	{% if location.name %}
	<strong>{{ location.name }}</strong><br/>
	{% endif %}
	{{ location.street }} {{ location.house_number }}<br/>
	{{ location.zipcode }} {{ location.city }}
      </div>

      <div class="mb-2">
	{{ location.county }}<br/>
	{{ location.state }}<br/>
	{{ location.country }}
      </div>

      {% if location.note %}
      <div class="mb-2">
	<i>{{ location.note }}</i>
      </div>
      {% endif %}

      {% if location.accessible %}
      <div class="mb-2">
	<i class="fa fa-wheelchair" aria-hidden="true"></i>
	{% trans "Barrierefreier Zugang" %}
      </div>
      {% endif %}

      {% if location.creator == request.user %}
      <div class="d-grid gap-2 mt-2">
	<a class="btn btn-secondary" href="{% url 'location:edit' location.pk %}">
	  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans "Bearbeiten" %}
	</a>
      </div>
      {% endif %}

      {% if location.ini_loc.count|add:location.ev_loc.count %}
      <div class="mt-4">
	<h6>{% trans 'Dieser Ort wird verwendet von' %}</h6>
	<ul class="fa-ul">
	  {% for ini in location.ini_loc.all %}
	  <li>
	    <i class="fa-li fa fa-fw fa-users" aria-hidden="true"></i>
	    <a href="{% url 'initiative:detail' ini.pk %}">{{ ini }}</a>
	  </li>
	  {% endfor %}
	</ul>
	<ul class="fa-ul">
	  {% for ev in location.ev_loc.all %}
	  <li>
	    <i class="fa-li fa fa-fw fa-calendar" aria-hidden="true"></i>
	    <a href="{% url 'event:detail' ev.pk %}">{{ ev }}</a>
	  </li>
	  {% endfor %}
	</ul>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock content %}

gemeinsam/location/templates/location/edit.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<h2>{% trans "Ort bearbeiten" %}</h2>

<ul class="nav nav-tabs">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" data-bs-target="#address" data-bs-toggle="tab"
	    type="button" role="tab" aria-controls="address" aria-selected="true">
      {% trans "Adresse" %}
    </button>
  </li>
  {% if form.instance.pk %}
  <li class="nav-item ms-auto">
    <button class="nav-link" data-bs-target="#delete" data-bs-toggle="tab"
	    type="button" role="tab" aria-controls="delete" aria-selected="false">
      {% trans "Löschen" %}
    </button>
  </li>
  {% endif %}
</ul>

<form role="form" method="POST">
  {% csrf_token %}

  <div class="row mt-3">
    <div class="col-12">
      <div class="tab-content">

	<!-- address -->
	<div id="address" class="tab-pane fade show active">
	  <h3>{% trans 'Adresse' %}</h3>
	  {% include 'location/location_form.html' %}
	</div>
	<!-- end address -->

	{% if form.instance.pk %}
	<div id="delete" class="tab-pane fade">
	  <h3>{% trans "Löschen" %}</h3>

          {% if form.instance.ini_loc.count|add:form.instance.ev_loc.count == 0 %}
	  <p class="help-block">
	    {% blocktrans %}
	    Willst du diesen Ort wirklich löschen? Dann bestätige dies bitte
	    mit einem Häkchen.
	    {% endblocktrans %}
	  </p>
	  <p class="text-danger">
	    {% trans 'Der Ort wird dann ohne weitere Nachfrage unwiderruflich gelöscht!' %}
	  </p>
	  <div class="checkbox">
	    <label>
	      {{ form.deletion }} {{ form.deletion.label }}
	    </label>
	  </div>
	  {% else %}
	  <p class="help-block">
	    {% blocktrans %}
	    Dieser Ort kann nicht gelöscht werden, weil er noch referenziert
	    wird
	    {% endblocktrans %}
	  </p>
	  <ul class="fa-ul">
	    {% if form.instance.pk %}
	    {% for ini in form.instance.ini_loc.all %}
	    <li>
	      <i class="fa-li fa fa-fw fa-users" aria-hidden="true"></i>
	      <a href="{% url 'initiative:edit' ini.pk %}">{{ ini }}</a>
	    </li>
	    {% endfor %}
	    {% endif %}
	  </ul>
	  <ul class="fa-ul">
	    {% if from.instance.pk %}
	    {% for ev in form.instance.ev_loc.all %}
	    <li>
	      <i class="fa-li fa fa-fw fa-calendar" aria-hidden="true"></i>
	      <a href="{% url 'event:edit-event' ev.pk %}">{{ ev }}</a>
	    </li>
	    {% endfor %}
	    {% endif %}
	  </ul>
	  {% endif %}
	</div>
	<!-- end deletion -->
	{% endif %}

      </div>

      <hr/>
      <div class="mt-3">
	<input class="btn btn-primary col-4 col-md-3 col-lg-2 me-2" type="submit" value="{% trans 'Speichern' %}" formnovalidate>
	<input class="btn btn-secondary col-4 col-md-3 col-lg-2" type="cancel" value="{% trans 'Abbrechen' %}" onclick="javascript:window.history.back()">
      </div>

    </div>
  </div>
</form>

{% endblock content %}

gemeinsam/location/templates/location/location_form.html
{% load i18n %}
{% load static %}
{% load leaflet_tags %}
{% block css %}
{% if settings.PELIAS_URL %}
{% leaflet_css plugins="forms,pelias-leaflet-geocoder" %}
{% else %}
{% leaflet_css plugins="forms,leaflet-control-geocoder" %}
{% endif %}
<link rel="stylesheet" href="{% static 'leaflet-defaulticon-compatibility/dist/leaflet-defaulticon-compatibility.css' %}"/>
{% endblock css %}
{% block js %}
{% if settings.PELIAS_URL %}
{% leaflet_js plugins="forms,pelias-leaflet-geocoder" %}
{% else %}
{% leaflet_js plugins="forms,leaflet-control-geocoder" %}
{% endif %}
<script type="text/javascript" src="{% static 'leaflet-defaulticon-compatibility/dist/leaflet-defaulticon-compatibility.min.js' %}"></script>
<script type="text/javascript" src="{% static 'location/format-coords.js' %}"></script>
<script type="text/javascript" src="{% static 'location/address-coords.js' %}"></script>
{% endblock js %}

{{ map_strings|json_script:"map-strings" }}
{{ geocode2modelfield|json_script:"geocode2modelfield" }}
{{ settings|json_script:"settings" }}
{{ region_force|json_script:"region-force" }}
{% url 'location:get_address' as url %}{{ url|json_script:"get-address-url" }}

<div class="row">
  {% if form.non_field_errors %}
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label={% trans "Schließen" %}>
      <span aria-hidden="true">&times;</span>
    </button>
    <ul class="list-group">
      {% for error in form.non_field_errors %}
      <li class="list-group-item">{{ error|safe }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}

  <div class="col-12">
    <p class="help-block">
      {% blocktrans %}
      Du kannst auf zwei Arten eine Adresse eingeben
      {% endblocktrans %}
    </p>
    <ol>
      <li>
	{% blocktrans %}
	Du tippst in das Suchfeld am unteren Rand der Karte eine
	geographische Angabe (z.B. Spektral oder eine Adresse) und
	wählst aus den Vorschlägen den passenden Ort aus.
	{% endblocktrans %}
      </li>
      <li>
	{% blocktrans %}
	Du setzt den Marker an die entsprechende Stelle auf der Karte. Klicke
	auf das Markersymbol <i class="fa fa-map-marker" aria-hidden="true"></i>
	auf der linken Seite der Karte. Danach klicke in der Karte auf deinen
	gewünschten Ort. Während der Marker schwebt, kannst du weiterhin die
	Karte zoomen und verschieben.
	{% endblocktrans %}
      </li>
    </ol>
    <p class="help-block">
      {% blocktrans %}
      Die gefunde Adresse wird dir unterhalb der Karte angezeigt. Du kannst
      diese nun benennen, eine Bemerkung hinzufügen und angeben, ob dieser
      Ort barrierefrei zugänglich ist.
      {% endblocktrans %}
    </p>
  </div>

  <div class="col-12">
    <div class="mb-3 required {% if form.coords.errors %}text-danger{% endif %}">
      <label for="{{ form.coords.id_for_label }}">
	{{ form.coords.label }}
      </label>
      {{ form.coords }}
    </div>
  </div>

  <div class="col-12">
    <div class="mb-3">
      <div class="row gy-3">
	<div class="col-12 col-sm-4">
	  <div class="form-floating">
	    {{ form.name }}
	    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
	  </div>
	</div>
	<div class="col-12 col-sm-8">
	  <div class="form-floating">
	    {{ form.note }}
	    <label for="{{ form.note.id_for_label }}">{{ form.note.label }}</label>
	  </div>
	</div>
      </div>
    </div>

    <div class="mb-3">
      <div class="row">
	<div class="col-12">
	  <label class="control-label" for="{{ form.accessible.id_for_label }}">
	    {{ form.accessible.label }}
	  </label>
	  {{ form.accessible }}
	</div>
      </div>
    </div>

    <hr/>

    <div class="mb-3">
      <div class="row gy-3">
	<div class="col-12 col-sm-8">
	  <div class="form-floating">
	    {{ form.street }}
	    <label for="{{ form.street.id_for_label }}">{{ form.street.label }}</label>
	  </div>
	</div>
	<div class="col-12 col-sm-4">
	  <div class="form-floating">
	    {{ form.house_number }}
	    <label  for="{{ form.house_number.id_for_label }}">
	      {{ form.house_number.label }}
	    </label>
	  </div>
	</div>
      </div>
    </div>

    <div class="mb-3">
      <div class="row gy-3">
	<div class="col-12 col-sm-4">
	  <div class="form-floating">
	    {{ form.zipcode }}
	    <label for="{{ form.zipcode.id_for_label }}">
	      {{ form.zipcode.label }}
	    </label>
	  </div>
	</div>
	<div class="col-12 col-sm-8">
	  <div class="form-floating">
	    {{ form.city }}
	    <label for="{{ form.city.id_for_label }}">
	      {{ form.city.label }}
	    </label>
	  </div>
	</div>
      </div>
    </div>

    <div class="mb-3">
      <div class="row gy-3">
	<div class="col-12 col-sm-4">
	  <div class="form-floating">
	    {{ form.county }}
	    <label for="{{ form.county.id_for_label }}">
	      {{ form.county.label }}
	    </label>
	  </div>
	</div>
	<div class="col-12 col-sm-4">
	  <div class="form-floating">
	    {{ form.state }}
	    <label for="{{ form.state.id_for_label }}">
	      {{ form.state.label }}
	    </label>
	  </div>
	</div>
	<div class="col-12 col-sm-4">
	  <div class="form-floating">
	    {{ form.country }}
	    <label for="{{ form.country.id_for_label }}">
	      {{ form.country.label }}
	    </label>
	  </div>
	</div>
      </div>

    </div>
  </div>

  <div class="col">
    <p class="help-block">
      {% blocktrans %}
      Falls du mit der Adressangabe nicht zufrieden bist, melde dies bitte
      bei der Moderation unter möglichst genauer Angabe (z.B. screenshot)
      der falschen und gewünschten Adresse per email an
      {% endblocktrans %}
      <a href="mailto:{{ settings.MODERATION_EMAIL }}">{{ settings.MODERATION_EMAIL }}</a>.
    </p>
  </div>
</div>

{% comment %}
{% include "location/address-coord_js.html" %}
{% endcomment %}