gemeinsam/event/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views
from .models import Event

app_name = "event"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path(
        "occurrence/<int:pk>/",
        views.DetailOccurrenceView.as_view(),
        name="detail-occurrence",
    ),
    path("add/<int:init>/", views.edit, name="add-event"),
    path("edit/<int:id>/", views.edit, name="edit-event"),
    path("calendar/", views.calendar, name="calendar"),
    path("events/", views.events, name="events"),
    path("map/", views.map, name="map"),
    path(
        "data.geojson",
        views.EventMapView.as_view(
            model=Event,
            properties=("title", "topics", "next_occurrence_weekday", "popup_content"),
            geometry_field="coords",
        ),
        name="data",
    ),
]

gemeinsam/faq/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views

app_name = "faq"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("new/", views.new, name="new"),
]

gemeinsam/gemeinsam/urls.py
# Standard Library
import os

# Django stuff
from django.conf import settings

# from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin, flatpages
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import JavaScriptCatalog

# Third party
import home_page

# from newsletter.models import Subscription
# from newsletter_subscription.backend import ModelBackend
# from newsletter_subscription.urls import newsletter_subscriptions_urlpatterns
from pictures.conf import get_settings

# First party
from common import views

urlpatterns = [
    # start-page
    path("", home_page.view),
    path("admin/", admin.site.urls),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("accounts/", include("registration.backends.default.urls")),
    path("accounts/profile/", include("profiles.urls")),
    path("topic/", include("topic.urls")),
    path("initiative/", include("initiative.urls")),
    path("faq/", include("faq.urls")),
    # favicon/robots
    path(
        "favicon.ico",
        RedirectView.as_view(
            url=os.path.join(settings.STATIC_URL, "img", "favicon.ico"), permanent=True
        ),
    ),
    path(
        r"robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # calendar
    path("event/", include("event.urls")),
    # locations
    path("location/", include("location.urls")),
    # search page
    path("search/", include("watson.urls")),
    path("about-us/", flatpages.views.flatpage, {"url": "/about-us/"}, name="about-us"),
    path(
        "participate/",
        flatpages.views.flatpage,
        {"url": "/participate/"},
        name="participate",
    ),
    path("filters/", views.filters),
    # captcha
    path("captcha/", include("captcha.urls")),
]

urlpatterns += [
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if get_settings().USE_PLACEHOLDERS:
    urlpatterns += [
        path("_pictures/", include("pictures.urls")),
    ]

gemeinsam/initiative/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views
from .models import Initiative

app_name = "initiative"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("line/", views.IndexView.as_view(), name="index-line"),
    path("bycounty/", views.IndexViewByCounty.as_view(), name="bycounty"),
    path("bycounty/line", views.IndexViewByCounty.as_view(), name="bycounty-line"),
    path("bytopic/", views.IndexViewByTopic.as_view(), name="bytopic"),
    path("bytopic/line", views.IndexViewByTopic.as_view(), name="bytopic-line"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("add/", views.edit, name="add"),
    path("edit/<int:id>/", views.edit, name="edit"),
    path("update/<str:token>/", views.update, name="update"),
    path(
        "picture-upload/<int:ini>/",
        views.PictureUploadView.as_view(),
        name="picture-upload",
    ),
    path("picture-delete/", views.PictureUploadView.as_view(), name="picture-delete"),
    path("user_list/<int:id>/", views.user_list, name="user_list"),
    path("map/<int:pk>", views.map, name="map-zoom"),
    path("map/", views.map, name="map"),
    path(
        "data.geojson",
        views.InitiativeMapView.as_view(
            model=Initiative,
            properties=("popup_content", "background"),
            geometry_field="coords",
        ),
        name="data",
    ),
]

gemeinsam/profiles/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views

app_name = "profile"
urlpatterns = [
    path("contacts/", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("", views.myself, name="myself"),
    path("edit/", views.edit, name="edit"),
    path("delete/", views.delete, name="delete"),
    path("events.ics", views.EventFeed(), name="my-events"),
]

gemeinsam/topic/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views

app_name = "topic"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:id>/", views.detail, name="detail"),
]

gemeinsam/templates/base.html
{% load static %}
{% load compress %}
{% load i18n %}
{% load cookielaw_tags %}
{% load common_tags %}
<!DOCTYPE html>
<html lang="de" {% block htmlattr %}{% endblock htmlattr %}>
  <head>
    <title>{% block title %}{{ appearance.title|default:"Gemeinsam Jetzt" }}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google-site-verification" content="AJGvlQuN3YWzRYa4xDSplC1eXiYF1sZE11Ks5NMIdyw" />
    {% block extra_head %}{% endblock %}

    {% if appearance.favicon %}
    <link rel="icon" type="image/x-icon" href="{{ appearance.favicon.favicon.url }}?v={{ appearance.update|date:'Ymd' }}"/>
    {% elif appearance.logo %}
    <link rel="icon" type="image/x-icon" href="{{ appearance.logo.favicon.url }}?v={{ appearance.update|date:'Ymd' }}"/>
    {% else %}
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}?v=1.0"/>
    {% endif %}

    {% compress css %}
    <link type="text/x-scss" href="{% static 'scss/theme.scss' %}" rel="stylesheet" media="screen">
    {% endcompress %}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'fork-awesome/css/fork-awesome.min.css' %}"/>
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'css/cookielaw.css' %}"/>
    {% block css %}{% endblock %}

    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
    <script type="text/javascript" src="{% static 'jquery/dist/jquery.min.js' %}"></script>
  </head>

  <body>
    {% cookielaw_banner %}
    <div id="top" class="sticky-top d-print-none">
      <nav class="navbar navbar-expand navbar-light bg-light" id="login-bar">
	<div class="container">
	  <form class="d-flex" action="{% url 'watson:search' %}">
	    <div class="input-group">
	      <input type="text" class="form-control form-control-sm"
		     name="q" placeholder='{% trans "Themen, Initiativen ..." %}'>
	      <button class="btn btn-primary" type="submit">
		<i class="fa fa-search" aria-hidden="true"></i>
	      </button>
	    </div>
	  </form>

	  <ul class="nav nav-pills">
            {% if user.is_authenticated %}
            <li role="presentation" class="nav-item dropdown">
	      <a class="nav-link dropdown-toggle" href="#"
		 data-bs-toggle="dropdown" aria-expanded="false">
		{% if user.profile.picture %}
		<img class="img-rounded" width="24" height="24" alt="{% trans 'Avatar' %}"
		     src="{{ user.profile.picture.mini.url }}">
		&nbsp;&nbsp;
		{% endif %}
		{{ user.get_full_name|default:user.username }}
	      </a>

	      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown-menu">
		<li>
		  <a class="dropdown-item" href="{% url 'profile:myself' %}">{% trans "Mein Profil" %}</a>
		</li>
		<li>
		  <a class="dropdown-item" href="{% url 'profile:myself' %}#initiative">{% trans "Meine Initiativen" %}</a>
		</li>
		<li>
		  <a class="dropdown-item" href="{% url 'profile:myself' %}#event">{% trans "Meine Veranstaltungen" %}</a>
		</li>
		<li>
		  <a class="dropdown-item"
		     href="{% url 'profile:myself' %}#location">{% trans "Meine Orte" %}</a>
		</li>
		{% if user.is_staff %}
		<li role="separator" class="dropdown-divider"></li>
		<li>
		  <a class="dropdown-item" href="{% url 'admin:index' %}">{% trans 'Admin' %}</a>
		</li>
		{% endif %}
		<li role="separator" class="dropdown-divider"></li>
		<li>
		  <a class="dropdown-item" href="{% url 'auth_logout' %}">{% trans 'Ausloggen' %}</a>
		</li>
	      </ul>
            </li>
	    {% else %}
	    <li role="presentation" class="nav-item dropdown d-md-none">
	      <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">
		<i class="fa fa-user"></i>
	      </a>
	      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdown-menu">
		<li>
		  <a class="dropdown-item" href="{% url 'auth_login' %}">{% trans 'Einloggen' %}</a>
		</li>
		<li><hr class="dropdown-divider"></li>
		<li>
		  <a class="dropdown-item" href="{% url 'registration_register' %}">{% trans 'Registrieren' %}</a>
		</li>
	      </ul>
	    </li>
	    <li class="nav-item d-none d-md-inline">
	      <a class="nav-link" href="{% url 'auth_login' %}">{% trans 'Einloggen' %}</a>
	    </li>
            <li class="nav-item d-none d-md-inline">
	      <a class="nav-link" href="{% url 'registration_register' %}">{% trans 'Registrieren' %}</a>
	    </li>
            {% endif %}
          </ul>
	</div>
      </nav>

      <nav id="header-nav" class="color-bar">
	<div class="container">
          <!-- MOBILE NAV -->
          <div class="navbar d-md-none">
            <!-- Brand and toggle get grouped for better mobile display -->
	    <a class="navbar-brand me-auto" href="/">
	      <img height="35" src="{% if appearance.logo %}{{ appearance.logo.standard.url }}{% else %}{% static 'img/gemeinsam_logo.png' %}{% endif %}">
	    </a>

            <button type="button" class="navbar-toggler" data-bs-toggle="collapse"
                    data-bs-target="#main-menu" aria-controls="main-menu"
		    aria-expanded="false" aria-label="{% trans 'Hauptmenü' %}">
	      <span>
		<i class="fa fa-bars fa-2x"></i>
	      </span>
            </button>
	  </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse" id="main-menu">
	    <ul class="navbar-nav">
	      <li class="nav-item">
                <a href="{% url 'topic:index' %}">
                  <h3><i class="fa fa-globe"></i> Themen</h3>
                </a>
	      </li>
	      <li class="nav-item">
                <a href="{% url 'event:calendar' %}">
                  <h3><i class="fa fa-calendar"></i> Kalender</h3>
                </a>
	      </li>
	      <li class="nav-item">
                <a href="{% url 'initiative:index' %}">
                  <h3><i class="fa fa-users"></i> Initiativen</h3>
                </a>
	      </li>
	      <li class="nav-item">
                <a href="{% url 'about-us' %}">
                  <h3><i class="fa fa-heartbeat"></i> Wir</h3>
                </a>
	      </li>
	      <li class="nav-item">
                <a href="{% url 'profile:index' %}">
                  <h3><i class="fa fa-commenting-o"></i> reden</h3>
                </a>
		</li>
	      <li class="nav-item">
                <a href="{% url 'participate' %}">
                  <h3><i class="fa fa-user-plus"></i> mit</h3>
                </a>
		</li>
	    </ul>
	  </div>

          <!-- DESKTOP NAV -->
          <div class="nav-table d-none d-md-table">
            <div class="nav-row">
              <div class="nav-cell">
		<a href="{% url 'topic:index' %}" title="Themen">
                  <i class="fa fa-globe fa-3x"></i>
                  <h3>Themen</h3>
		</a>
              </div>
              <div class="nav-cell">
		<a href="{% url 'event:calendar' %}" title="Kalender">
                  <i class="fa fa-calendar fa-3x"></i>
                  <h3>Kalender</h3>
		</a>
              </div>
              <div class="nav-cell">
		<a href="{% url 'initiative:index' %}" title="Initiativen">
                  <i class="fa fa-users fa-3x"></i>
                  <h3>Initiativen</h3>
		</a>
              </div>
              <div class="nav-cell">
		<a href="/" id="logo">
                  <img src="{% if appearance.logo %}{{ appearance.logo.standard.url }}{% else %}{% static 'img/gemeinsam_logo.png' %}{% endif %}" class="" alt="Logo" title="Logo">
		</a>
              </div>

              <div class="nav-cell">
		<a href="{% url 'about-us' %}" title="Wir">
                  <i class="fa fa-heartbeat fa-3x"></i>
                  <h3>Wir</h3>
		</a>
              </div>
              <div class="nav-cell">
		<a href="{% url 'profile:index' %}" title="Reden">
                  <i class="fa fa-commenting-o fa-3x"></i>
                  <h3>reden</h3>
		</a>
              </div>
              <div class="nav-cell">
		<a href="{% url 'participate' %}" title="Mit">
                  <i class="fa fa-user-plus fa-3x"></i>
                  <h3>mit</h3>
		</a>
              </div>
            </div>
          </div>
	</div>
      </nav>
    </div>

    <div class="container" id="content">
      {% block content %}{% endblock %}
    </div>

    <div class="d-none">
      <a rel="me" href="https://graz.social/@gemeinsampunktjetzt">Mastodon</a>
    </div>

    <div id="footer" class="d-print-none">
      <!-- footer first nav -->
      <nav class="navbar navbar-expand-md color-bar footer-upper-nav fs-5">
        <div class="container">
	  <div class="d-flex justify-content-between w-100" id="upper-menu">
            <ul class="navbar-nav">
	      {% for item in menu_above.menuentry_set.all %}
	      {% if item.order < 0 %}
	      <li class="nav-item">
		{% if item.link %}
		<a class="nav-link" href="{{ item.link }}"{% if item.link|slice:":4" == "http" %} target="_blank" rel="noopener noreferrer"{% endif %}>{{ item.text|safe }}</a>
		{% else %}
		<span class="nav-link">{{ item.text|safe }}</span>
		{% endif %}
	      </li>
	      {% endif %}
	      {% endfor %}
            </ul>
            <ul class="navbar-nav">
	      {% for item in menu_above.menuentry_set.all %}
	      {% if item.order >= 0 %}
	      <li class="nav-item ms-auto text-end">
		{% if item.link %}
		<a class="nav-link" href="{{ item.link }}"{% if item.link|slice:":4" == "http" %} target="_blank" rel="noopener noreferrer"{% endif %}>{{ item.text|safe }}</a>
		{% else %}
		<span class="nav-link">{{ item.text|safe }}</span>
		{% endif %}
	      </li>
	      {% endif %}
	      {% endfor %}
            </ul>
	  </div>
	</div>
      </nav>

      <!-- topics -->
      <div id="footer-topics">
        <div class="container">
          <div class="d-flex flex-row justify-content-evenly">
            {% for topic in topic_list %}
            <div>
              <p>
                <a href="{% url 'topic:detail' topic.pk %}">
                  <img class="icon-secondary" src="{{ topic.icon.small.url }}" alt="{{ topic }}">
                </a>
              </p>
              <p class="d-none d-md-block fs-5">
                <a href="{% url 'topic:detail' topic.pk %}">{{ topic|upper }}</a>
              </p>
              <p class="d-none d-lg-block fs-6">
                {% for st in topic.subtopic_set.all %}
                <a class=''
                   href="{% url 'topic:detail' topic.pk %}#{{ st|slugify }}">{{ st.name|nbsp }}</a><br/>
                {% endfor %}
              </p>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>

      <!-- lower menu -->
      <nav class="navbar navbar-expand-md color-bar fs-5">
        <div class="container">
	  <div class="d-flex justify-content-between w-100" id="lower-menu">
            <ul class="navbar-nav">
	      {% for item in menu_below.menuentry_set.all %}
	      {% if item.order < 0 %}
	      <li class="nav-item">
		{% if item.link %}
		<a class="nav-link" href="{{ item.link }}"{% if item.link|slice:":4" == "http" %} target="_blank" rel="noopener noreferrer"{% endif %}>{{ item.text|safe }}</a>
		{% else %}
		<span class="nav-link">{{ item.text|safe }}</span>
		{% endif %}
	      </li>
	      {% endif %}
	      {% endfor %}
            </ul>
            <ul class="navbar-nav">
	      {% for item in menu_below.menuentry_set.all %}
	      {% if item.order >= 0 %}
	      <li class="nav-item ms-auto text-end">
		{% if item.link %}
		<a class="nav-link" href="{{ item.link }}"{% if item.link|slice:":4" == "http" %} target="_blank" rel="noopener noreferrer"{% endif %}>{{ item.text|safe }}</a>
		{% else %}
		<span class="nav-link">{{ item.text|safe }}</span>
		{% endif %}
	      </li>
	      {% endif %}
	      {% endfor %}
            </ul>
          </div>
	</div>
      </nav>
    </div>

    <div id="side-buttons" class="d-print-none">
      <div class="d-flex flex-md-column flex-row">
	<a class="btn btn-primary" href="/participate/" role="button"><i class="fa fa-user-plus"></i> Mitmachen</a>
	<a class="btn btn-secondary" href="/pages/support/" role="button"><img class="align-middle" src="{% static 'img/donate.png' %}"> Spenden</a>
      </div>
    </div>

    <script type="text/javascript" src="{% static 'js/search.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/cookielaw.js' %}"></script>
    <script type="text/javascript" src="{% static '@popperjs/core/dist/umd/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>

    {% block js %}{% endblock %}

    <script type="text/javascript" src="{% static 'js/scroll.js' %}"></script>

    {% if MATOMO_SERVER %}
    <!-- Matomo -->
    <input type="hidden" id="matomo" value="{{ MATOMO_SERVER }}">
    <script type="text/javascript" src="{% static 'js/matomo.js' %}"></script>
    {% endif %}
  </body>
</html>

gemeinsam/templates/home.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block title %}{{ appearance.title|default:"Gemeinsam Jetzt" }}{% endblock title %}

{% block js %}
<script type="text/javascript" src="{% static 'js/clamp.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/clamp.js' %}"></script>
{% endblock js %}


{% block content %}
<div class="front-page">
  <h1>
    {{ appearance.motto|default:"Ge&shy;stal&shy;ten wir un&shy;sere Zu&shy;kunft!" }}
  </h1>
  <h5>
    Achtsamkeit ⋅ Menschenwürde ⋅ Partizipation ⋅ Solidarität ⋅ Zukunftsfähigkeit
  </h5>

  <h2>
    Informieren - Inspirieren - Mitmachen
  </h2>

  <h4>Los geht&apos;s</h4>
  <h3>&gt;Hier Initiativen, Projekte und Gruppen finden&lt;</h3>

  <div class="row mb-5 gy-5 text-center text-uppercase" id="circles">
    <div class="col-12 col-md-4">
      <div class="position-relative">
	<a href="{% url 'topic:index' %}">
	  <img class="icon-primary" src="{% static 'img/circle.png' %}" width="80%"/>
	  <img class="icon-secondary centered" src="{% static 'img/topics.png' %}" width="40%"/>
	</a>
      </div>
      <a href="{% url 'topic:index' %}">
	<h2 class="">{% trans 'Themen' %}</h2>
      </a>
    </div>
    <div class="col-12 col-md-4">
      <div class="position-relative">
	<a href="{% url 'initiative:map' %}">
	  <img class="icon-primary" src="{% static 'img/circle.png' %}" width="80%"/>
	  <img class="icon-secondary centered" src="{% static 'img/regions.png' %}" width="60%"/>
	</a>
      </div>
      <a href="{% url 'initiative:map' %}">
	<h2 class="">{% trans 'Regionen' %}</h2>
      </a>
    </div>
    <div class="col-12 col-md-4">
      <div class="position-relative">
	<a href="{% url 'initiative:index' %}">
	  <img class="icon-primary" src="{% static 'img/circle.png' %}" width="80%"/>
	  <img class="icon-secondary centered" src="{% static 'img/initiative.png' %}" width="40%"/>
	</a>
      </div>
      <a href="{% url 'initiative:index' %}">
	<h2 class="">{% trans 'Initiativen' %}</h2>
      </a>
    </div>
  </div>

  <section id="front-page-search" class="mt-4">
    <div class="row justify-content-center">
      <div class="col-10">
	<form action="{% url 'watson:search' %}">
	  <div class="input-group">
	    <input type="text" class="form-control input-lg"
		   name="q" placeholder='{% trans "Themen, Veranstaltungen, Initiativen, ..." %}'>
            <button class="btn btn-primary" type="submit">
	      <i class="fa fa-search" aria-hidden="true"></i>
            </button>
	  </div>
	</form>
      </div>
    </div>
  </section>

  {% if initiative_list %}
  <h4>{% trans "Initiativen des Tages" %}</h4>
  <div class="row">
    {% for ini in initiative_list %}
    {% include 'initiative/card.html' %}
    {% endfor %}
  </div>
  {% endif %}


  <h4>{% trans 'Wir machen dei&shy;ne Ini&shy;tia&shy;tive & dein En&shy;ga&shy;ge&shy;ment sicht&shy;bar' %}</h4>
  <img class="img-fluid" src="{% static 'img/fingers.png' %}" alt="Finger">
  <h3>Du bist eine Initiative oder Gruppe und möchtest Dich hier eintragen?</h3>
  <div class="text-primary fs-3 d-flex flex-column flex-sm-row justify-content-around">
    <div class="flex-even">
      1
      <div>Registriere dich als Person</div>
      <a class="btn btn-secondary" href="{% url 'registration_register' %}">
	{% trans 'Registrieren' %}
      </a>
    </div>
    <div class="flex-even">
      2
      <div>Lege dann deine Initiative, Projekt oder Gruppe an</div>
      <a class="btn btn-secondary" href="{% url 'initiative:add' %}">
	{% trans 'Initiative anlegen' %}
      </a>
    </div>
    <div class="flex-even">
      3
      <div>
	Wir prüfen ganz kurz, ob Ihr zu den Haltungen und Zielen von gemeinsam.jetzt passt
      </div>
    </div>
  </div>
  <div class="fs-3 text-primary">
    Keine Kosten - Keine Werbung - Kein Datenmissbrauch - Unabhängig
  </div>

  <h4>Mit&shy;ei&shy;nan&shy;der re&shy;den</h4>
  <img class="img-fluid" src="{% static 'img/communicate.png' %}" alt="Miteinander reden">
  <div class="text-primary fs-3 lh-sm d-flex flex-column flex-sm-row justify-content-around">
    <div class="flex-even">
      <div class="mb-2">Videokonferenzen für Gruppen</div>
      <div class="mb-2">Oder Videotelefonie mit einer Person</div>
      <div class="mb-2">Direkt im Browser</div>
      <a class="btn btn-secondary" href="https://jitsi.gemeinsam.jetzt" target="_blank">jitsi</a>
    </div>
    <div class="flex-even">
      <div class="mb-2">Handy, Laptop, Webbrowser</div>
      <div class="mb-2">Du brauchst keine Telefonnummer</div>
      <a class="btn btn-secondary" href="https://element.gemeinsam.jetzt" target="_blank">element</a>
      <a class="btn btn-secondary" href="/media/uploads/2020/10/01/Guide_ELEMENTmatrix-gemeinsamjetzt_2020-10-04.pdf">Anleitung</a>
    </div>
    <div class="flex-even">
      <div class="mb-2">Einfach und schnell</div>
      <div class="mb-2">Zeitgleich gemeinsam bearbeiten</div>
      <div class="mb-2">Von <a class="text-secondary" href="https://info.graz.social" target="_blank">graz.social</a> freundlich zur Verfügung gestellt</div>
      <a class="btn btn-secondary" href="https://pad.graz.social" target="_blank">etherpad</a>
    </div>
  </div>
  <div class="fs-3 text-primary">
    Alle 3 Tools sind datensicher, kostenlos & Open Source!
  </div>

  <h4 class="text-break">wir.gemeinsam.jetzt</h4>
  <img class="img-fluid" src="{% static 'img/team.png' %}" alt="Team">
  <div class="text-primary fs-3 lh-sm row">
    <div class="col-12 col-md-6">
      <h6>Ziele</h6>
      <div class="mb-2">Räume der Begegnung</div>
      <div class="mb-2">Sichtbarmachen von Initiativen</div>
      <div class="mb-2">Gemeinsame Entwicklung der Angebote</div>
    </div>
    <div class="col-12 col-md-6">
      <h6>Angebot</h6>
      <div class="mb-2">Webplattform</div>
      <div class="mb-2">Kommunikationstools</div>
      <div class="mb-2">Regionale Initiativen-Vernetzung</div>
      <div class="mb-2">Begleitung gemeinsamer Entscheidungsfindung</div>
    </div>
    <div class="col-12 col-md-6">
      <h6>Unterstütze!</h6>
      <div class="mb-2">Zeit & Engagement</div>
      <div class="mb-2">
	<a class="text-secondary" href="/pages/support">Spenden</a>
	<br/>
	<strong>IBAN: AT32 2081 5000 4138 1021</strong><br>
	BIC: STSPAT2GXXX
      </div>
    </div>
    <div class="col-12 col-md-6">
      <h6>Fragen?</h6>
      <div class="mb-2">
	Mail:
	<a class="text-secondary" href="mailto:wir@gemeinsam.jetzt">
	  wir@gemeinsam.jetzt
	</a>
      </div>
      <div class="mb-2">
	Matrix:
	<a class="text-secondary" target="_blank" href="https://matrix.to/#/#sgj:gemeinsam.jetzt">
	  #sgj:gemeinsam.jetzt
	</a>
      </div>
      <div class="mb-2">
	<a class="text-secondary" href="/faq">Häufig gestellte Fragen</a>
      </div>
    </div>
  </div>

</div>

{% endblock content %}