gemeinsam/event/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views
from .models import Event

app_name = "event"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path(
        "occurrence/<int:pk>/",
        views.DetailOccurrenceView.as_view(),
        name="detail-occurrence",
    ),
    path("add/<int:init>/", views.edit, name="add-event"),
    path("edit/<int:id>/", views.edit, name="edit-event"),
    path("calendar/", views.calendar, name="calendar"),
    path("events/", views.events, name="events"),
    path("map/", views.map, name="map"),
    path(
        "data.geojson",
        views.EventMapView.as_view(
            model=Event,
            properties=("title", "topics", "next_occurrence_weekday", "popup_content"),
            geometry_field="coords",
        ),
        name="data",
    ),
]

gemeinsam/faq/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views

app_name = "faq"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("new/", views.new, name="new"),
]

gemeinsam/gemeinsam/urls.py
# Standard Library
import os

# Django stuff
from django.conf import settings

# from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin, flatpages
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import JavaScriptCatalog

# Third party
import home_page

# from newsletter.models import Subscription
# from newsletter_subscription.backend import ModelBackend
# from newsletter_subscription.urls import newsletter_subscriptions_urlpatterns
from pictures.conf import get_settings

# First party
from common import views

urlpatterns = [
    # start-page
    path("", home_page.view),
    path("admin/", admin.site.urls),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("accounts/", include("registration.backends.default.urls")),
    path("accounts/profile/", include("profiles.urls")),
    path("topic/", include("topic.urls")),
    path("initiative/", include("initiative.urls")),
    path("faq/", include("faq.urls")),
    # favicon/robots
    path(
        "favicon.ico",
        RedirectView.as_view(
            url=os.path.join(settings.STATIC_URL, "img", "favicon.ico"), permanent=True
        ),
    ),
    path(
        r"robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # calendar
    path("event/", include("event.urls")),
    # locations
    path("location/", include("location.urls")),
    # search page
    path("search/", include("watson.urls")),
    path("about-us/", flatpages.views.flatpage, {"url": "/about-us/"}, name="about-us"),
    path(
        "participate/",
        flatpages.views.flatpage,
        {"url": "/participate/"},
        name="participate",
    ),
    path("filters/", views.filters),
    # captcha
    path("captcha/", include("captcha.urls")),
]

urlpatterns += [
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if get_settings().USE_PLACEHOLDERS:
    urlpatterns += [
        path("_pictures/", include("pictures.urls")),
    ]

gemeinsam/initiative/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views
from .models import Initiative

app_name = "initiative"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("line/", views.IndexView.as_view(), name="index-line"),
    path("bycounty/", views.IndexViewByCounty.as_view(), name="bycounty"),
    path("bycounty/line", views.IndexViewByCounty.as_view(), name="bycounty-line"),
    path("bytopic/", views.IndexViewByTopic.as_view(), name="bytopic"),
    path("bytopic/line", views.IndexViewByTopic.as_view(), name="bytopic-line"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("add/", views.edit, name="add"),
    path("edit/<int:id>/", views.edit, name="edit"),
    path("update/<str:token>/", views.update, name="update"),
    path(
        "picture-upload/<int:ini>/",
        views.PictureUploadView.as_view(),
        name="picture-upload",
    ),
    path("picture-delete/", views.PictureUploadView.as_view(), name="picture-delete"),
    path("user_list/<int:id>/", views.user_list, name="user_list"),
    path("map/<int:pk>", views.map, name="map-zoom"),
    path("map/", views.map, name="map"),
    path(
        "data.geojson",
        views.InitiativeMapView.as_view(
            model=Initiative,
            properties=("popup_content", "background"),
            geometry_field="coords",
        ),
        name="data",
    ),
]

gemeinsam/topic/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views

app_name = "topic"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:id>/", views.detail, name="detail"),
]

gemeinsam/event/views.py
# Standard Library
import datetime as dt
import json

# Django stuff
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied, ViewDoesNotExist
from django.db.models import Q
from django.http import HttpResponseBadRequest, HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.timezone import now
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

# Third party
from djgeojson.views import GeoJSONLayerView

# First party
from initiative.models import Initiative
from location.apps import GEOCODE2MODELFIELD, MAP_STRINGS
from location.forms import LocationForm

# Local imports
from .forms import EventForm
from .models import Event, Occurrence


def ajax_required(f):
    """AJAX request required decorator use it in your views.

    @ajax_required
    def my_view(request):
        ....

    """

    def wrap(request, *args, **kwargs):
        if not request.headers.get("x-requested-with") == "XMLHttpRequest":
            return HttpResponseBadRequest()
        return f(request, *args, **kwargs)

    wrap.__doc__ = f.__doc__
    wrap.__name__ = f.__name__
    return wrap


class DetailView(generic.DetailView):
    model = Event
    context_object_name = "event"
    template_name = "event/detail.html"

    def get_context_data(self, **kwargs):
        # Django stuff
        from django.conf import settings

        context = super(DetailView, self).get_context_data(**kwargs)
        context["moderation_mail"] = getattr(
            settings, "MODERATION_EMAIL", "moderation@gemeinsam.jetzt"
        )
        return context


class DetailOccurrenceView(generic.DetailView):
    model = Occurrence
    context_object_name = "occurrence"
    template_name = "event/detail.html"

    def get_context_data(self, **kwargs):
        # Django stuff
        from django.conf import settings

        context = super(DetailOccurrenceView, self).get_context_data(**kwargs)
        context["event"] = self.get_object().event
        context["moderation_mail"] = getattr(
            settings, "MODERATION_EMAIL", "moderation@gemeinsam.jetzt"
        )
        return context


@login_required
def edit(request, id=None, init=None):
    if id:
        event = get_object_or_404(Event, pk=id)
        # check permission
        if not request.user.has_perm("event.change_event", event):
            raise PermissionDenied
        initiative = event.initiative

    elif init:
        initiative = get_object_or_404(Initiative, pk=init)
        # check permission
        if not request.user.has_perm("initiative.add_event", initiative):
            raise PermissionDenied
        event = Event(initiative=initiative, creator=request.user)
    else:
        raise ViewDoesNotExist

    location_form = LocationForm(prefix="loc")

    if request.method == "POST":
        data = request.POST.copy()
        # first check if user wants to delete this event
        if request.POST.get("deletion"):
            event.delete()
            return HttpResponseRedirect("/")

        location_id = int(request.POST.get("location"))
        # remove location data for non-physical locations
        if location_id < 0:
            del data["location"]

        if location_id == 0:
            location_form = LocationForm(data=data, prefix="loc")

            if location_form.is_valid():
                new_location = location_form.save(commit=False)
                new_location.creator = request.user
                new_location.save()
                data["location"] = "{}".format(new_location.id)

        event_form = EventForm(data=data, instance=event)

        if event_form.is_valid():
            # save the event
            event_new = event_form.save(commit=False)
            if (
                initiative.published and not initiative.moderation
            ) or initiative.abbr == "n/a":
                event_new.published = True
            event_new.on_line = location_id == -1
            event_new.save()
            event_form.save_m2m()

            return HttpResponseRedirect(reverse("event:detail", args=[event_new.pk]))

    else:
        event_form = EventForm(instance=event, user=request.user)

    return render(
        request,
        "event/edit.html",
        {
            "event_form": event_form,
            "location_form": location_form,
            "map_strings": MAP_STRINGS,
            "geocode2modelfield": GEOCODE2MODELFIELD,
            "settings": {
                "MODERATION_EMAIL": settings.MODERATION_EMAIL,
                "PELIAS_API_KEY": settings.PELIAS_API_KEY,
                "PELIAS_URL": settings.PELIAS_URL,
            },
        },
    )


def calendar(request):
    return render(request, "event/calendar.html")


@csrf_exempt
@ajax_required
def events(request):
    start = request.POST.get("start", "2016-01-01")
    end = request.POST.get("end", now() + dt.timedelta(days=365))
    occurrences = Occurrence.objects.filter(
        start_time__lte=end, end_time__gte=start, event__published=True
    ).prefetch_related(
        "event", "event__topics", "event__topics__parent", "event__initiative"
    )
    ret = []

    # check filters
    topic_ids = request.POST.getlist("topics[]", [])
    county_names = request.POST.getlist("counties[]", [])
    initiative = request.POST.get("initiative", "")
    person = request.POST.get("person", "")
    accessible = json.loads(request.POST.get("accessible", "false"))
    off_line = json.loads(request.POST.get("off_line", "false"))
    non_recurring = json.loads(request.POST.get("non_recurring", "false"))

    if topic_ids:
        occurrences = occurrences.filter(event__topics__in=topic_ids).distinct()

    if county_names:
        county_query = Q(
            event__location__county__in=[x.split(":")[-1] for x in county_names]
        )
        on_line_query = Q(event__on_line=True)
        occurrences = occurrences.filter(county_query | on_line_query)

    if initiative:
        occurrences = occurrences.filter(
            event__initiative__name__icontains=initiative
        ) | occurrences.filter(event__initiative__abbr__icontains=initiative)
    if person:
        occurrences = (
            occurrences.filter(event__initiative__admin__first_name__icontains=person)
            | occurrences.filter(event__initiative__admin__last_name__icontains=person)
            | occurrences.filter(event__initiative__contact_person__icontains=person)
        )

    if accessible:
        accessible_query = Q(event__location__accessible=True) | Q(event__on_line=True)
        occurrences = occurrences.filter(accessible_query)

    if off_line:
        off_line_query = Q(event__on_line=False)
        occurrences = occurrences.filter(off_line_query)

    for occ in occurrences:
        if not non_recurring or not occ.event.recurring():
            ret.append(
                {
                    "title": occ.title,
                    "start": occ.start_time,
                    "end": occ.end_time,
                    "list_content": occ.list_content,
                    "popup_content": occ.popup_content,
                }
            )
    return JsonResponse(ret, safe=False)


@method_decorator(csrf_exempt, name="dispatch")
class EventMapView(GeoJSONLayerView):
    def post(self, request, *args, **kwargs):
        self.context = {
            "start": request.POST.get("start", now().replace(hour=0, minute=0)),
            "end": request.POST.get("end", now() + dt.timedelta(days=7)),
            "topic_ids": request.POST.getlist("topics[]", []),
            "county_names": [
                x.split(":")[-1] for x in request.POST.getlist("counties[]", [])
            ],
            "initiative": request.POST.get("initiative", ""),
            "person": request.POST.get("person", ""),
            "accessible": json.loads(request.POST.get("accessible", "false")),
        }
        return super(EventMapView, self).render_to_response(self.context)

    def get_queryset(self):
        ret = Event.objects.filter(
            published=True,
            coords__isnull=False,
            occurrence__start_time__range=(self.context["start"], self.context["end"]),
        ).prefetch_related("initiative")

        if self.context["topic_ids"]:
            ret = ret.filter(topics__in=self.context["topic_ids"]).distinct()

        if self.context["county_names"]:
            ret = ret.filter(location__county__in=self.context["county_names"])

        if self.context["initiative"]:
            ret = ret.filter(
                initiative__name__icontains=self.context["initiative"]
            ) | ret.filter(initiative__abbr__icontains=self.context["initiative"])

        if self.context["person"]:
            ret = (
                ret.filter(
                    initiative__admin__first_name__icontains=self.context["person"]
                )
                | ret.filter(
                    initiative__admin__last_name__icontains=self.context["person"]
                )
                | ret.filter(
                    initiative__contact_person__icontains=self.context["person"]
                )
            )

        if self.context["accessible"]:
            ret = ret.filter(location__accessible=True)

        return ret


def map(request):
    return render(request, "event/map.html")

gemeinsam/event/templates/event/calendar-header.html
{% load i18n %}
<h1>{% trans 'Ver&shy;an&shy;stal&shy;tungs&shy;ka&shy;len&shy;der' %}</h1>

<p class="lead">
  {% blocktrans %}
  Wann, wo, was in deiner Umgebung stattfindet kannst Du hier in einer
  Kalender- oder Kartenansicht finden. Der Kalender zeigt dir einen
  Tag oder eine Terminübersicht an - klicke direkt auf den Termin um
  Details zu lesen.
  {% endblocktrans %}
</p>

{% comment %}
<p class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong>COVID-19-Maßnahmen</strong>: Bitte informiert euch selbst
  direkt bei den Veranstalter*innen, ob und wie die jeweilige Veranstaltung
  stattfindet.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</p>
{% endcomment %}

<div class="btn-toolbar justify-content-between" role="toolbar">
  <div class="btn-group" role="group">
    <a class="btn btn-outline-primary btn-md{% if view == 'cal' %} active{% endif %}"
       {% if view == "map" %}href="{% url 'event:calendar' %}"{% endif %}>
      {% trans "Kalender" %}
    </a>
    <a class="btn btn-outline-primary btn-md{% if view == 'map' %} active{% endif %}"
       {% if view == "cal" %}href="{% url 'event:map' %}"{% endif %}>
      {% trans "Karte" %}
    </a>
  </div>

  <div class="btn-group" role="group">
    {% include 'filter/filter-button.html' %}
  </div>
</div>

{% include 'filter/filter-modal.html' %}

gemeinsam/event/templates/event/calendar-list-view.html
<td width="18%">
  <div class="fs-4 fw-bold lh-sm">
    {{ occ.start_time|date:"H:i" }} &ndash; {{ occ.end_time|date:"H:i" }}
    {% if occ.event.recurring %}
    <span class="text-muted ms-1 fs-5">
      <i class="fa fa-repeat"></i>
    </span>
    {% endif %}
  </div>
  <div class="fs-5 lh-sm">
    {% if occ.start_time|date:"YMd" == occ.end_time|date:"YMd" %}
    {{ occ.start_time|date:"l, j. F"}}
    {% else %}
    {{ occ.start_time|date:"l, j. F"}} &ndash; {{ occ.end_time|date:"l, j. F"}}
    {% endif %}
  </div>
</td>

<td width="68%">
  <div class="mb-1">
    <a class="text-black fs-4 fw-bold lh-sm" href="{% url 'event:detail' occ.event.pk %}">{{ occ }}</a>
  </div>
  <div>
    <a class="fs-5 lh-sm"href="{% url 'initiative:detail' occ.initiative.pk %}">{{ occ.initiative }}</a>
  </div>
  <div class="fs-5 lh-sm">
    {{ occ.event.location.address_formatted }}
  </div>
</td>

<td width="14%" align="right" valign="middle">
  <ul class="list-group list-group-horizontal justify-content-end">
    {% for st in occ.event.topics.all %}
    {% ifchanged st.parent %}
    <li class="list-group-item border-0 px-1">
      <a href="{% url 'topic:detail' st.parent.pk %}#{{ st|slugify }}">
	<img
	  class="icon-secondary" src="{{ st.parent.icon.url }}"
	  title="{{ st }}"
	  alt="{{ st.parent }}"
	  height="24">
      </a>
    </li>
    {% endifchanged %}
    {% endfor %}
  </ul>
</td>

gemeinsam/event/templates/event/calendar-tooltip.html
{% load i18n %}
<!-- title -->
<h4>
  <a href="{% url 'event:detail' event.pk %}">{{ event }}</a>
  {% if event.recurring %}
  <small>
    <span class="badge bg-secondary"><i class="fa fa-repeat"></i></span>
  </small>
  {% endif %}
  {% if event.location.accessible %}
  <small>
    <span class="badge bg-secondary"><i class="fa fa-wheelchair"></i></span>
  </small>
  {% endif %}
</h4>

<!-- topics -->
<div class="mb-1">
  <ul class="list-inline">
    {% for st in event.topics.all %}
    <li class="list-inline-item">
      <a href="{% url 'topic:detail' st.parent.pk %}#{{ st|slugify }}">
	<img class="icon-secondary align-baseline"
	     src="{{ st.parent.icon.url }}"
	     title="{{ st.parent }}"
	     alt="{{ st.parent }}"
	     height="14"> {{ st }}
      </a>
    </li>
    {% endfor %}
  </ul>
</div>

<!-- event info -->
<div class="">
  <ul class="fa-ul">
    {% if event.initiative.abbr != 'n/a' %}
    <li>
      <i class="fa-li fa fa-fw fa-users" aria-hidden="true"></i>
      <a href="{% url 'initiative:detail' event.initiative.pk %}">{{ event.initiative }}</a>
    </li>
    {% endif %}
    <li>
      <i class="fa-li fa fa-fw fa-map-marker" aria-hidden="true"></i>
      {% with location=event.location on_line=event.on_line%}
      {% include 'location/address.html' %}
      {% endwith %}
    </li>
    {% if event.recurring %}
    {% if occurrence %}
    <li>
      <i class="fa-li fa fa-fw fa-clock-o" aria-hidden="true"></i>
      {% with start=occurrence.start_time end=occurrence.end_time %}
      {% include 'event/daterange.html' %}
      {% endwith %}
    </li>
    {% elif event.next_occurrence %}
    <li>
      <i class="fa-li fa fa-fw fa-clock-o" aria-hidden="true"></i>
      {% trans 'Nächster Termin' %}:
      {% with start=event.next_occurrence.start_time end=event.next_occurrence.end_time %}
      {% include 'event/daterange.html' %}
      {% endwith %}
    </li>
    {% endif %}
    {% else %}
    <li>
      <i class="fa-li fa fa-fw fa-clock-o" aria-hidden="true"></i>
      {% with start=event.start_time end=event.end_time %}
      {% include 'event/daterange.html' %}
      {% endwith %}
    </li>
    {% endif %}
  </ul>
</div>

gemeinsam/event/templates/event/calendar.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Veranstaltungen" %}{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'fullcalendar/dist/fullcalendar.min.css' %}"/>
<link rel="stylesheet" href="{% static 'qtip2/dist/jquery.qtip.min.css' %}"/>
{% endblock css %}

{% block js %}
<script type="text/javascript" src="{% static 'moment/min/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'moment/locale/de-at.js' %}"></script>
<script type="text/javascript" src="{% static 'fullcalendar/dist/fullcalendar.min.js' %}"></script>
<script type="text/javascript" src="{% static 'fullcalendar/dist/locale/de-at.js' %}"></script>
<script type="text/javascript" src="{% static 'qtip2/dist/jquery.qtip.min.js' %}"></script>
<script type="text/javascript" src="{% static 'event/calendar.js' %}"></script>
{% endblock js %}

{% block content %}
<section class="text-center">
  {% include 'event/calendar-header.html' with view='cal' %}

  <div class="row mt-3">
    <div class="col-12">
      <div id="calendar"></div>
    </div>
  </div>

</section>

{% endblock content %}

gemeinsam/event/templates/event/card.html
{% load rules %}
{% load i18n %}
{% load common_tags %}
{% load static %}

{% if user.is_authenticated %}
{% has_perm 'event.change_event' request.user event as can_edit_event %}
{% endif %}

<div class="col-md-4 col-12 mb-3 px-2 text-start"
     data-topics="{% for st in ini.topics.all %}{{ st.pk }} {% endfor %}"
     data-county="{{ ini.location.state}}:{{ ini.location.county }}"
     data-names="{{ ini.name|lower }} {{ ini.abbr|lower }}"
     data-persons="{{ ini.admin.get_full_name|lower }} {{ ini.contact_person|lower }}"
     data-accessible="{{ ini.location.accessible }}">
  <div class="card h-100">

    <div class="card-body">
      <!-- logo and name -->
      <div class="row mb-2">
	<div class="col-sm-3 col-2">
	  <div class="">
	    <a href="{% url 'initiative:detail' event.initiative.pk %}">
	      <img class="img-thumbnail" width="100" src="{% if event.initiative.logo %}{{ event.initiative.logo.thumbnail.url }}{% else %}{% static 'img/no-ini-logo.png' %}{% endif %}" alt="{{ event.initiative }}">
	    </a>
	  </div>
	</div>
	<div class="col-sm-9 col-10">
	  <div class="fs-4 text-truncate">
	    <a href="{% url 'event:detail' event.pk %}">{{ event }}</a>
	  </div>
	</div>
      </div>

      <!-- topics -->
      <div class="mb-1">
	{% include 'event/topics-list.html' %}
      </div>

      <!-- event info -->
      <div class="mb-2 text-truncate">
	<ul class="fa-ul">
	  {% if event.initiative.abbr != 'n/a' %}
	  <li>
	    <i class="fa-li fa fa-fw fa-users" aria-hidden="true"></i>
	    <a href="{% url 'initiative:detail' event.initiative.pk %}">{{ event.initiative }}</a>
	  </li>
	  {% endif %}
	  <li>
	    <i class="fa-li fa fa-fw fa-map-marker" aria-hidden="true"></i>
	    {% with location=event.location on_line=event.on_line%}
	    {% include 'location/address.html' %}
	    {% endwith %}
	  </li>
	  <li>
	    <i class="fa-li fa fa-fw fa-clock-o" aria-hidden="true"></i>
	    {% if event.recurring %}
	    {% trans 'nächster Termin' %}:
	    {% with start=event.next_occurrence.start_time end=event.next_occurrence.end_time %}
	    {% include 'event/daterange.html' %}
	    {% endwith %}
	    {% else %}
	    {% with start=event.start_time end=event.end_time %}
	    {% include 'event/daterange.html' %}
	    {% endwith %}
	    {% endif %}
	  </li>
	</ul>
      </div>

      <!-- description -->
      <div class="row">
	<div class="clamp">
	  {{ event.description|html2text }}
	</div>
      </div>
    </div>

    {% if can_edit_event %}
    <div class="card-footer">
      <a class="btn btn-sm btn-secondary"
	 href="{% url 'event:edit-event' event.pk %}"
	 title="{% trans 'Veranstaltung bearbeiten' %}">
	<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
	{% trans 'Bearbeiten' %}
      </a>
    </div>
    {% endif %}

  </div>
</div>

gemeinsam/event/templates/event/daterange.html
{{ start|date:"l, j. F Y, H:i" }} &ndash;
{% if start|date:"YMd" == end|date:"YMd" %}
{{ end|date:"H:i"}}
{% else %}
{{ end|date:"l, j. F Y, H:i" }}
{% endif %}

gemeinsam/event/templates/event/map.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load leaflet_tags %}
{% load geojson_tags %}

{% block css %}
{% leaflet_css %}
<link rel="stylesheet" href="{% static 'fullcalendar/dist/fullcalendar.min.css' %}"/>
<link rel="stylesheet" href="{% static 'event/hidden-cal.css' %}"/>
{% endblock css %}

{% block js %}
{% leaflet_js %}
<script type="text/javascript" src="{% static 'moment/min/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'moment/locale/de-at.js' %}"></script>
<script type="text/javascript" src="{% static 'fullcalendar/dist/fullcalendar.min.js' %}"></script>
<script type="text/javascript" src="{% static 'fullcalendar/dist/locale/de-at.js' %}"></script>
<script type="text/javascript" src="{% static 'js/map.js' %}"></script>
{% endblock js %}

{% block content %}
<section class="text-center">
  {% include 'event/calendar-header.html' with view='map' %}

  <div class="row mt-3">
    <div class="col-12">

      {% comment %}
      use the fullcalendars navigation but hide the calendar view
      by means of css (event/hidden-cal.css)
      {% endcomment %}
      <div id="calendar"></div>

      <div class="card mb-4">
	{% leaflet_map "large-map" %}
      </div>
    </div>
  </div>

  <div id="map-info" url="{% url 'event:data' %}" lat="0" lon="0"></div>

</section>

{% endblock content %}

gemeinsam/event/templates/event/topics-list.html
{% load i18n %}
{% load rules %}

{% if user.is_authenticated %}
{% has_perm 'event.change_event' request.user event as can_edit_event %}
{% endif %}

<ul class="list-inline">
  {% for st in event.topics.all %}
  <li class="list-inline-item lead">
    <a href="{% url 'topic:detail' st.parent.pk %}#{{ st|slugify }}">
      <img class="icon-secondary align-baseline"
	   src="{{ st.parent.icon.url }}"
	   title="{{ st.parent }}"
	   alt="{{ st.parent }}"
	   height="16"> {{ st }}
    </a>
  </li>
  {% empty %}
  {% if can_edit_event %}
  <a class="link-warning" href="{% url 'event:edit-event' event.pk %}?tab=topics">
    {% trans 'Themen hinzufügen' %}
  </a>
  {% endif %}
  {% endfor %}
</ul>