gemeinsam/event/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views
from .models import Event

app_name = "event"
urlpatterns = [
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path(
        "occurrence/<int:pk>/",
        views.DetailOccurrenceView.as_view(),
        name="detail-occurrence",
    ),
    path("add/<int:init>/", views.edit, name="add-event"),
    path("edit/<int:id>/", views.edit, name="edit-event"),
    path("calendar/", views.calendar, name="calendar"),
    path("events/", views.events, name="events"),
    path("map/", views.map, name="map"),
    path(
        "data.geojson",
        views.EventMapView.as_view(
            model=Event,
            properties=("title", "topics", "next_occurrence_weekday", "popup_content"),
            geometry_field="coords",
        ),
        name="data",
    ),
]

gemeinsam/faq/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views

app_name = "faq"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("new/", views.new, name="new"),
]

gemeinsam/gemeinsam/urls.py
# Standard Library
import os

# Django stuff
from django.conf import settings

# from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin, flatpages
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import JavaScriptCatalog

# Third party
import home_page

# from newsletter.models import Subscription
# from newsletter_subscription.backend import ModelBackend
# from newsletter_subscription.urls import newsletter_subscriptions_urlpatterns
from pictures.conf import get_settings

# First party
from common import views

urlpatterns = [
    # start-page
    path("", home_page.view),
    path("admin/", admin.site.urls),
    path("ckeditor5/", include("django_ckeditor_5.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("accounts/", include("registration.backends.default.urls")),
    path("accounts/profile/", include("profiles.urls")),
    path("topic/", include("topic.urls")),
    path("initiative/", include("initiative.urls")),
    path("faq/", include("faq.urls")),
    # favicon/robots
    path(
        "favicon.ico",
        RedirectView.as_view(
            url=os.path.join(settings.STATIC_URL, "img", "favicon.ico"), permanent=True
        ),
    ),
    path(
        r"robots.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # calendar
    path("event/", include("event.urls")),
    # locations
    path("location/", include("location.urls")),
    # search page
    path("search/", include("watson.urls")),
    path("about-us/", flatpages.views.flatpage, {"url": "/about-us/"}, name="about-us"),
    path(
        "participate/",
        flatpages.views.flatpage,
        {"url": "/participate/"},
        name="participate",
    ),
    path("filters/", views.filters),
    # captcha
    path("captcha/", include("captcha.urls")),
]

urlpatterns += [
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if get_settings().USE_PLACEHOLDERS:
    urlpatterns += [
        path("_pictures/", include("pictures.urls")),
    ]

gemeinsam/initiative/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views
from .models import Initiative

app_name = "initiative"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("line/", views.IndexView.as_view(), name="index-line"),
    path("bycounty/", views.IndexViewByCounty.as_view(), name="bycounty"),
    path("bycounty/line", views.IndexViewByCounty.as_view(), name="bycounty-line"),
    path("bytopic/", views.IndexViewByTopic.as_view(), name="bytopic"),
    path("bytopic/line", views.IndexViewByTopic.as_view(), name="bytopic-line"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("add/", views.edit, name="add"),
    path("edit/<int:id>/", views.edit, name="edit"),
    path("update/<str:token>/", views.update, name="update"),
    path(
        "picture-upload/<int:ini>/",
        views.PictureUploadView.as_view(),
        name="picture-upload",
    ),
    path("picture-delete/", views.PictureUploadView.as_view(), name="picture-delete"),
    path("user_list/<int:id>/", views.user_list, name="user_list"),
    path("map/<int:pk>", views.map, name="map-zoom"),
    path("map/", views.map, name="map"),
    path(
        "data.geojson",
        views.InitiativeMapView.as_view(
            model=Initiative,
            properties=("popup_content", "background"),
            geometry_field="coords",
        ),
        name="data",
    ),
]

gemeinsam/profiles/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views

app_name = "profile"
urlpatterns = [
    path("contacts/", views.index, name="index"),
    path("<int:pk>/", views.detail, name="detail"),
    path("", views.myself, name="myself"),
    path("edit/", views.edit, name="edit"),
    path("delete/", views.delete, name="delete"),
    path("events.ics", views.EventFeed(), name="my-events"),
]

gemeinsam/topic/urls.py
# Django stuff
from django.urls import path

# Local imports
from . import views

app_name = "topic"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:id>/", views.detail, name="detail"),
]

gemeinsam/initiative/models.py
# -*- coding: utf-8 -*-
# Standard Library
import datetime

from functools import partial
from io import BytesIO

# Django stuff
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.core.files.base import ContentFile
from django.db.models.signals import post_init, post_save
from django.template.loader import render_to_string
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _

# Third party
from django_bleach.models import BleachField
from phonenumber_field.modelfields import PhoneNumberField
from pictures.models import PictureField
from PIL import Image
from stdimage import StdImageField
from stdimage.utils import render_variations

# First party
from location.models import Location
from topic.models import SubTopic


class Initiative(models.Model):
    LEGAL_FORMS = (
        (None, _("Nicht angegeben")),
        (1, _("Verein")),
        (2, _("Unternehmen")),
        (3, _("Öffentliche Einrichtung")),
        (4, _("Genossenschaft")),
        (5, _("Bündnis")),
    )
    BACKGROUND = (
        (None, _("----")),
        (1, _("öffentliche Einrichtung")),
        (2, _("konfessionell")),
        (3, _("parteipolitisch")),
        (4, _("gewerblich")),
    )
    YES_NO = ((True, _("Ja")), (False, _("Nein")))

    # general
    name = models.CharField(
        _("Name"), max_length=100, help_text=_("Name der Initiative")
    )
    slug = models.SlugField(_("Slug"), max_length=110, unique=True)
    abbr = models.CharField(
        _("Abkürzung"),
        max_length=10,
        blank=True,
        help_text=_("Abkürzung der Initiative"),
    )
    logo = StdImageField(
        _("Logo der Initiative"),
        upload_to="initiative/logos",
        null=True,
        blank=True,
        variations={
            "thumbnail": (100, 100, True),
            "square": (300, 300, True),
            "large": (640, 480),
            "medium": (480, 360),
        },
    )

    # description
    aim = BleachField(verbose_name=_("Ziel"), help_text=_("Was wir erreichen wollen"))
    activity = BleachField(
        verbose_name=_("Aktivitäten"), help_text=_("Wie wir dorthin kommen wollen")
    )
    contribution = BleachField(
        verbose_name=_("Beteiligung"), help_text=_("Wie du dich einbringen kannst")
    )
    note = BleachField(
        verbose_name=_("Anmerkungen"),
        help_text=_("Was wir sonst noch sagen wollen"),
        blank=True,
    )

    # contact
    website = models.URLField(_("Website"), blank=True)
    mail = models.EmailField(_("Email"), blank=True)
    phone = PhoneNumberField(_("Telefon"), max_length=40, blank=True)
    matrix_room = models.CharField(
        _("Öffentlicher [matrix] Raum"), max_length=100, blank=True
    )
    contact_person = models.CharField(
        _("Kontaktperson"),
        max_length=50,
        blank=True,
        help_text=_("Name der Ansprechperson"),
    )

    # address - fk to location and coords will be reduntantly stored here
    # because of geodjango that needs to have a geometric field
    location = models.ForeignKey(
        Location,
        related_name="ini_loc",
        on_delete=models.PROTECT,
        verbose_name=_("Ort"),
    )
    coords = models.PointField(
        _("Geographische Koordinaten"), srid=4326, dim=2, blank=True, null=True
    )

    # miscellaneous
    legal_form = models.SmallIntegerField(
        _("Organisationsform"), choices=LEGAL_FORMS, blank=True, null=True
    )
    size = models.IntegerField(
        _("Größe"), help_text=_("Anzahl der aktiven Mitglieder"), blank=True, null=True
    )

    # administrative
    admin = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="admin+",
        help_text=_("Administrator der Initiative"),
    )

    background = models.SmallIntegerField(
        _("Hintergrund"),
        choices=BACKGROUND,
        blank=True,
        null=True,
        default=None,
        help_text=_("Hintergrund der Initiative (moderierter Status)"),
    )
    moderation = models.BooleanField(
        verbose_name=_("Moderation"),
        choices=YES_NO,
        default=False,
        help_text=_("Moderation von Veranstaltungen, ..."),
    )

    # collaborators
    collaborators = models.ManyToManyField(
        User, through="Permission", verbose_name=_("MitarbeiterInnen")
    )

    # published
    published = models.BooleanField(
        _("Veröffentlicht"),
        help_text=_("Steckbrief öffentlich zugänglich"),
        choices=YES_NO,
        default=False,
    )
    reason = models.TextField(
        _("Grund für Nichtveröffentlichung"), blank=True, default=_("Neue Initiative")
    )

    create = models.DateField(_("Angelegt"), auto_now_add=True)
    update = models.DateField(_("Zuletzt aktualisiert"), auto_now=True)

    # topics
    topics = models.ManyToManyField(SubTopic, verbose_name=_("Themen"), blank=True)

    def __str__(self):
        return self.name

    def __init__(self, *args, **kwargs):
        super(Initiative, self).__init__(*args, **kwargs)

        for field in ["aim", "activity", "contribution", "note"]:
            verbose_name = "get_{}_verbose_name".format(field)
            help_text = "get_{}_help_text".format(field)

            curried_verbose_name = partial(self._get_verbose_name, field)
            curried_help_text = partial(self._get_help_text, field)

            setattr(self, verbose_name, curried_verbose_name)
            setattr(self, help_text, curried_help_text)

    @classmethod
    def from_db(cls, db, field_names, values):
        instance = super(Initiative, cls).from_db(db, field_names, values)
        instance._loaded_values = dict(list(zip(field_names, values)))
        return instance

    def save(self, *args, **kwargs):
        self.coords = self.location.coords
        self.slug = self._get_unique_slug()
        if self.published:
            self.reason = ""
        super(Initiative, self).save(*args, **kwargs)

    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Initiative.objects.filter(slug=unique_slug).exists():
            unique_slug = f"{slug}-{num}"
            num += 1
        return unique_slug

    def _get_help_text(self, field_name):
        for field in self._meta.fields:
            if field.name == field_name:
                return field.help_text

    def _get_verbose_name(self, field_name):
        for field in self._meta.fields:
            if field.name == field_name:
                return field.verbose_name

    def first_letter(self):
        return self.name[0].upper()

    def get_absolute_url(self):
        return "/initiative/{}".format(self.pk)

    @property
    def popup_content(self):
        return render_to_string("initiative/map_tooltip.html", {"ini": self})

    class Meta:
        ordering = ["name"]

        verbose_name = _("Initiative")
        verbose_name_plural = _("Initiativen")


def email_notify(sender, instance, created, **kwargs):
    # Django stuff
    from django.conf import settings
    from django.contrib.sites.models import Site
    from django.core.mail import EmailMultiAlternatives
    from django.template import loader

    site = Site.objects.get_current()
    c = {"initiative": instance, "site": site}

    if created:
        subject = "[{}] {} - {}".format(site.name, _("Neue Initiative"), instance)

        # mail to moderation
        t = loader.get_template("initiative/new_initiative.txt")
        msg = EmailMultiAlternatives(
            subject, t.render(c), settings.SERVER_EMAIL, [settings.MODERATION_EMAIL]
        )
        msg.send()

        # mail from moderation to admin of the initiative
        t = loader.get_template("initiative/new_initiative_user.txt")
        msg = EmailMultiAlternatives(
            subject, t.render(c), settings.MODERATION_EMAIL, [instance.admin.email]
        )
        msg.send()

    else:
        # check if published state changed to True
        if not instance.previous_published_state and instance.published:
            subject = "[{}] {} - {}".format(
                site.name, _("Initiative veröffentlicht!"), instance
            )

            # mail from moderation to admin of the initiative
            # depending on the background
            t = loader.get_template("initiative/new_initiative_published.txt")
            msg = EmailMultiAlternatives(
                subject, t.render(c), settings.MODERATION_EMAIL, [instance.admin.email]
            )
            msg.send()

            # also publish events (if ini is not moderated)
            if not instance.moderation:
                for event in instance.events.all():
                    event.published = instance.published
                    event.save(update_ini=False)
            else:
                if instance.events.count() > 0:
                    # notify moderation about unpublished events
                    subject = "[{}] {}".format(site.name, instance)

                    t = loader.get_template("initiative/moderated_events.txt")
                    msg = EmailMultiAlternatives(
                        subject,
                        t.render(c),
                        settings.SERVER_EMAIL,
                        [settings.MODERATION_EMAIL],
                    )
                    msg.send()


post_save.connect(email_notify, sender=Initiative)


def check_published_state(sender, instance, **kwargs):
    instance.previous_published_state = instance.published


post_init.connect(check_published_state, sender=Initiative)


def resize_and_autorotate(file_name, variations, storage):
    with storage.open(file_name) as f:
        with Image.open(f) as image:
            file_format = image.format
            # png or gif do not have _getexif
            exif = getattr(image, "_getexif", lambda: None)()

            # if image has exif data about orientation, let's rotate it

gemeinsam/faq/views.py
# Django stuff
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic

# Local imports
from .models import Entry


# Create your views here.
class IndexView(generic.ListView):
    template_name = "faq/index.html"
    context_object_name = "entry_list"

    def get_queryset(self):
        return Entry.objects.filter(
            answer__isnull=False, published=True, category__isnull=False
        )


def new(request):
    if request.method == "POST":
        question = request.POST.get("new")
        if question:
            entry = Entry(question=question)
            entry.save()
            return render(request, "faq/question_entered.html")
        else:
            return render(request, "faq/question_invalid.html")

    else:
        return HttpResponseRedirect("/faq")

gemeinsam/initiative/templates/initiative/detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load email_obfuscator %}
{% load bleach_tags %}
{% load rules %}
{% load pictures %}

{% block htmlattr %}prefix="og: http://ogp.me/ns#"{% endblock htmlattr %}
{% block title %}{{ ini }}{% endblock title %}

{% block extra_head %}
<meta property="og:url" content="{{ SITE_URL }}{{ ini.get_absolute_url }}/">
{% if ini.logo.thumbnail.url %}
<meta property="og:image" content="{{ SITE_URL }}{{ ini.logo.square.url }}">
<meta property="og:image:secure_url" content="{{ SITE_URL }}{{ ini.logo.square.url }}">
<meta property="og:image:width" content="{{ ini.logo.square.width }}">
<meta property="og:image:height" content="{{ ini.logo.square.height }}">
<meta name="twitter:image" content="{{ SITE_URL }}{{ ini.logo.square.url }}">
{% endif %}
<meta property="og:title" content="{{ ini.name }}">
<meta property="og:type" content="website">
<meta property="og:description" content="{{ ini.aim|striptags }}">
<meta name="twitter:card" content="summary" />
{% endblock %}

{% block css %}
<link rel="stylesheet" type="text/css" media="all" href="{% static 'css/social.css' %}"/>
<link rel="stylesheet" href="{% static 'glider-js/glider.min.css' %}">
{% endblock css %}

{% block content %}

{% if user.is_authenticated %}
{% has_perm 'initiative.change_initiative' request.user ini as can_edit_initiative %}
{% has_perm 'initiative.add_event' request.user ini as can_add_event %}
{% endif %}

<section id="steckbrief">
  {% if not ini.published and not can_edit_initiative %}
  <h1>{{ ini }}</h1>
  <p class="alert alert-warning">
    {% trans 'Diese Initiative ist derzeit nicht veröffentlicht!' %}
  </p>
  {% else %}
  <div class="d-flex justify-content-between">
    <div>
      <h1 class="text-break">{{ ini }}</h1>
      <!-- topics -->
      <div>
	{% include 'initiative/topics-list.html' %}
      </div>
    </div>

    <!-- logo -->
    <div class="h1">
      {% if ini.logo %}
      <img class="img-thumbnail" width="100" src="{{ ini.logo.medium.url }}" alt="{{ ini }}">
      {% else %}
      <img class="img-thumbnail" width="100" src="{% static 'img/no-ini-logo.png' %}" alt="{% trans 'Kein Logo' %}">
      {% endif %}
      {% if ini.abbr %}
      <h5 class="mt-1">{{ ini.abbr }}</h5>
      {% endif %}
    </div>
  </div>

  <div class="row d-flex justify-content-around flex-md-row flex-column-reverse">
    <!-- steckbrief -->
    <div class="col-12 col-md-9 mt-3 mt-md-0">
      <h3><a name="aim"></a>{{ ini.get_aim_verbose_name }} <small>{{ ini.get_aim_help_text }}</small></h3>
      {{ ini.aim|bleach }}

      <h3><a name="activity"></a>{{ ini.get_activity_verbose_name }} <small>{{ ini.get_activity_help_text }}</small></h3>
      {{ ini.activity|bleach }}

      <h3><a name="contribution"></a>{{ ini.get_contribution_verbose_name }} <small>{{ ini.get_contribution_help_text }}</small></h3>
      {{ ini.contribution|bleach }}

      {% if ini.note %}
      <h3><a name="note"></a>{{ ini.get_note_verbose_name }} <small>{{ ini.get_note_help_text }}</small></h3>
      {{ ini.note|bleach }}
      {% endif %}
    </div>

    <div class="col-12 col-md-3">

      <!-- contact -->
      <h3>{% trans "Kontakt" %}</h3>
      <ul class="fa-ul">
        {% if ini.location.address_formatted %}
        <li>
          <i class="fa-li fa fa-fw fa-map-marker" aria-hidden="true"></i>
          <a href="{% url 'initiative:map-zoom' ini.pk %}">{{ ini.location.address_formatted }}</a>
        </li>
        {% endif %}
        {% if ini.contact_person %}
        <li>
          <i class="fa-li fa fa-fw fa-user" aria-hidden="true"></i>
          {{ ini.contact_person }}
        </li>
        {% endif %}
        {% if ini.website %}
        <li>
          <i class="fa-li fa fa-fw fa-globe" aria-hidden="true"></i>
          <a href="{{ ini.website }}" rel="noopener noreferrer" target="_blank">{{ ini.website }}</a>
        </li>
        {% endif %}
        {% if ini.mail %}
        <li>
          <i class="fa-li fa fa-fw fa-envelope-o" aria-hidden="true"></i>
          {{ ini.mail|obfuscate_mailto }}
        </li>
        {% endif %}
	{% if ini.matrix_room %}
	<li>
          <i class="fa-li fa fa-fw fa-matrix-org" aria-hidden="true"></i>
          <a href="{{ communication_tool.base_url }}{{ ini.matrix_room }}" target="_blank" rel="noopener noreferrer">
	    {{ ini.matrix_room }}
	  </a>
        </li>
        {% endif %}
        {% if ini.phone %}
        <li>
          <i class="fa-li fa fa-fw fa-phone" aria-hidden="true"></i>
          <a href="tel:{{ ini.phone|cut:" " }}">{{ ini.phone }}</a>
        </li>
        {% endif %}
      </ul>

      {% if ini.background or ini.legal_form or ini_size %}
      <h3>{% trans "Info" %}</h3>
      {% if ini.background %}
      <div class="mb-1">
	<span class="badge bg-secondary">{{ ini.get_background_display }}</span>
      </div>
      {% endif %}

      <ul class="list-unstyled">
	{% if ini.legal_form %}
	<li>
	  <b>{% trans 'Rechtsform' %}</b>:
	  {{ ini.get_legal_form_display }}
	</li>
	{% endif %}
	{% if ini.size %}
	<li>
	  <b>{% trans 'Aktive' %}</b>:
	  {{ ini.size }}
	</li>
	{% endif %}
      </ul>
      {% endif %}

      {% if user.is_authenticated %}
      <ul class="list-unstyled">
	<li>
	  <b>{% trans 'Admin' %}</b>:
	  <a href="{% url 'profile:detail' ini.admin.pk %}">{{ ini.admin.get_full_name|default:_("Kein Name angegeben") }}</a>
	</li>
	<li>
	  <b>{% trans 'Angelegt' %}</b>:
	  {{ ini.create|date:"Y-m-d" }}
	</li>
	<li>
	  <b>{% trans 'Aktualisiert' %}</b>:
	  {{ ini.update|date:"Y-m-d" }}
	</li>

	{% if can_edit_initiative %}
	{% if not ini.published %}
	<li>
	  <span class="badge bg-primary">{% trans 'Nicht veröffentlicht' %}</span>
	  {{ moderation_mail|obfuscate_mailto:"Nachfragen" }}
	</li>
	{% endif %}
	{% if ini.moderation %}
	<li>
	  <b>{% trans 'Moderierte Initiative' %}</b>
	  {{ moderation_mail|obfuscate_mailto:"Nachfragen" }}
	</li>
	{% endif %}
	{% endif %}
      </ul>
      {% endif %}

      {% if can_edit_initiative or can_add_event %}
      <div class="d-grid gap-2 mt-2">
	{% if can_edit_initiative %}
	<a class="btn btn-secondary" href="{% url 'initiative:edit' ini.pk %}">
	  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Bearbeiten' %}
	</a>
	{% endif %}
	{% if can_add_event %}
	<a class="btn btn-secondary" href="{% url 'event:add-event' ini.pk %}">
	  <i class="fa fa-calendar" aria-hidden="true"></i> {% trans 'Veranstaltung hinzufügen' %}
	</a>
	{% endif %}
      </div>
      {% endif %}

      <div class="mt-2">
	<a href="mailto:{{ moderation_mail }}?subject='{{ ini }}' {% trans 'als unangemessen melden' %}&body={% trans 'Hallo,%0A%0Aich möchte diese Initiative als unangemessen melden' %}:%0Ahttp://{{ request.META.HTTP_HOST }}{{ ini.get_absolute_url }}%0A%0AMit Bitte um Rückmeldung%0A">
	  <i class="fa fa-bell-o" aria-hidden="true" title="{% trans 'Eintrag als unangemessen melden' %}"></i>
	  {% trans 'Melden' %}
	</a>
      </div>

    </div>
  </div>


  <div class="row mt-3 g-5 d-print-none">
    {% if next_events %}
    <div class="col-12">
      <h3>{% trans 'Kommende Veranstaltungen' %}</h3>
      <div class="glider-contain multiple">
	<div class="glider row">
	  {% for occ in next_events %}
	  {% include 'event/card.html' with event=occ.event %}
	  {% endfor %}
	</div>

	<button role="button" aria-label="Previous" class="glider-prev"><i class="fa fa-chevron-left"></i></button>
	<button role="button" aria-label="Next" class="glider-next"><i class="fa fa-chevron-right"></i></button>
	<div class="dots"></div>
      </div>
    </div>
    {% endif %}

    {% if ini.picture_set.all %}
    <div class="col-12">
      <h3>{% trans "Bilder" %}</h3>

      <div id="carousel" class="carousel slide" data-bs-ride="carousel" data-interval="false">
	<div class="carousel-indicators">
	  {% for picture in ini.picture_set.all %}
	  <button type="button" data-bs-target="#carousel"
		  data-bs-slide-to="{{ picture.order }}"
		  {% if forloop.first %}class="active"{% endif %}
		  aria-current="true" aria-label="Slide {{ picture.order }}"></button>
	  {% endfor %}
	</div>

	<div class="carousel-inner">
	  {% for picture in ini.picture_set.all %}
	  <div class="carousel-item{% if forloop.first %} active{% endif %}">
	    {% picture picture.photo img_alt=picture.title img_loading="lazy" img_class="d-block" %}
	    <div class="carousel-caption d-none d-md-block">
	      <h5>{{ picture.title }}</h5>
	    </div>
	  </div>
	  {% endfor %}
	</div>

	<button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
	  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
	  <span class="visually-hidden">{% trans 'Voriges' %}</span>
	</button>
	<button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
	  <span class="carousel-control-next-icon" aria-hidden="true"></span>
	  <span class="visually-hidden">{% trans 'Nächstes' %}</span>
	</button>
      </div>
    </div>
    {% endif %}

    {% if ini.matrix_room %}
    <div class="col-12">
      <h3>
	{% trans "Öffentlicher Matrix Raum" %}
	<a href="{{ communication_tool.base_url }}{{ ini.matrix_room }}" target="_blank" rel="noopener noreferrer">
	  {{ ini.matrix_room }}
	</a>
      </h3>
      <matrix-live
	mail_address="webmaster@gemeinsam.jetzt"
	room-alias="{{ ini.matrix_room }}"
	initial-load="60"
	show-footer="true">
      </matrix-live>
      <script src="{% static 'initiative/matrix-live-min.js' %}"></script>
    </div>
    {% endif %}
  </div>

  <div id="social-buttons" class="row my-3">
    <div class="col-12 text-center">
      {% with obj=ini name=ini.name %}
      {% include 'social/social.html' %}
      {% endwith %}
    </div>
  </div>
  {% endif %}
</section>

{% endblock content %}

{% block js %}
<script type="text/javascript" src="{% static 'js/clamp.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/clamp.js' %}"></script>
<script type="text/javascript" src="{% static 'glider-js/glider.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/glider.js' %}"></script>
{% endblock js %}

gemeinsam/initiative/templates/initiative/initiative-users.html
{% if user_list %}
<ul class="list-inline">
  {% for user in user_list %}
  <li class="list-inline-item">
    <a href="{{ communication_tool.base_url }}{{ user.profile.matrix_id }}" target="_blank" rel="noopener noreferrer">{{ user.profile.matrix_id }}</a>
    (<a href="{% url 'profile:detail' user.pk %}">{{ user.first_name }} {{ user.last_name }}</a>)
  </li>
  {% endfor %}
</ul>
{% endif %}